name: I'm a test

on:
  workflow_dispatch:

jobs:
  auto-lock-sys-deps:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker pull ubuntu:focal
          docker manifest inspect ubuntu:focal
