name: I'm a test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - run: "exit 0"
  
  job2:
    name: Afterwards
    runs-on: ubuntu-20.04
    needs: [test]
    #if: needs.test.conclusion == 'success'
    steps:
      - run: "echo '${{ needs.test }}'"
