name: I'm a test

on:
  workflow_dispatch:

jobs:
  auto-lock-sys-deps:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: thejcannon
          password: ${{ secrets.DOCKER_PAT }}
      - run: |
          docker manifest inspect nvcr.io/nvidia/cuda:12.1.1-base-ubuntu20.04
