on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      pull-number:
        type: number
        required: true

jobs:
  trigger-job:
    name: Trigger the workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - run: gh workflow run test.yml --ref main -F pull-number=${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ github.token }}

  the-job:
    name: Name
    runs-on: ubuntu-latest
    environment: main
    steps:
      - run: 'echo "hi"'
