name: I'm a test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        include: [{"maybe_sleep": "sleep 20"}, {"maybe_sleep": ""}]
    runs-on: ubuntu-20.04
    steps:
      - run: |
          ${{ matrix.maybe_sleep }}
          exit 1
