name: Uploady

on:
  workflow_dispatch:
    inputs:
      version_match:
        description: "Version to match"
        required: true
        type: string

jobs:
  uploady:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: python -m venv .venv
      - run: .venv/bin/pip install pygithub
      - run: .venv/bin/python uploady.py ${{ inputs.version_match }}
        env:
          GH_TOKEN: ${{ secrets.GHTOK }}
