name: Uploady

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag"
        required: true
        type: string

jobs:
  uploady:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: python -m venv .venv
      - run: .venv/bin/pip install pygithub wheel
      - run: .venv/bin/python uploady.py ${{ inputs.tag }}
        env:
          GH_TOKEN: ${{ secrets.GHTOK }}
