name: Uploady

on: [workflow_dispatch]

jobs:
  uploady:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: python -m venv .venv
      - run: .venv/bin/pip install pygithub
      - run: .venv/bin/python uploady.py
        env:
          GH_TOKEN: ${{ secrets.GHTOK }}
